version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - product-analyzer-network

  backend:
    build:
      context: ../Product-Analyzer
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - product-analyzer-network

networks:
  product-analyzer-network:
    driver: bridge